- hosts: linuxvm
  become: yes
  
  tasks:
    - name: "Atualiza o SO"
      apt:
        update_cache: yes
        upgrade: yes

    - name: "Baixa o script de instalação Docker"
      shell: curl -fsSL https://get.docker.com -o get-docker.sh
      args:
        warn: false
    - name: "Instala o docker"
      shell: sh get-docker.sh

    - name: "Instala o python3 pip"
      apt:
        name:
          - python3-pip

    - name: "Instala o Module Docker Python"
      pip:
        name: docker

    - name: "Pull da imagem do Redis"
      docker_image:
        name: redis
        source: pull

    - name: "Cria container com Redis"
      docker_container:
        name: redis_container
        image: redis
        state: present
